Feature mail action custom tag
paperless-ngx/paperless-ngx pull request #1032
Opened 2022-05-26 12:06 UTC by pheerai

## Proposed change

For my personal use case, I found the existing mail rules a bit intrusive (moving files or changing other state I use to indicate something completely different).
This PR includes a new mail rule that will utilize IMAP keywords (often indicates as 'Tags' in frontends).
The implementation itself is rather simple, but some additional work had to go into the test, as `MailMessage`s `flags`-method is caching its output

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2022-05-26 15:18 UTC, stumpylog commented
Thank you for the PR.  To help us review just your changes, could you remove the changes which appear to be from `main`?

2022-05-26 15:41 UTC, pheerai commented
With pleasure, sorry for the non-clean branch, I should've caught that myself.

2022-05-27 20:06 UTC, stumpylog requested changes
Looks pretty good, just a couple things to look into

2022-06-02 14:44 UTC, stumpylog approved these changes

2022-06-02 16:46 UTC, merged