Info about installing on subpath
paperless-ngx/paperless-ngx pull request #1350
Opened 2022-08-02 18:21 UTC by viktor-c

## Proposed change

In my setup I want to use traefik as a reverse proxy. This works without problems on a subdomain, subdomain.example.com. Trying to make this work on a subpath, like subdomain.example.com/paperless fails. I could not get useful information just by searching. 
The standard way would be to setup Traefik to respond to subdomain.example.com/paperless, strip the pathprefix and send the query to paperless-ngx which waits on the root path and is unknowing of the domain it serves on. This however is not working as intended. 
The other way was to change the basepath, but this is very scarcely documented and it contains some errors like subdomain instead of subpath

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2022-08-02 20:23 UTC, viktor-c commented
@shamoon also uses paperless behind Traefik, do you have a setup with subdomain or subpath?

2022-08-02 21:18 UTC, shamoon commented
I use subdomain. Subpath always seems like more of a pain =)

Thanks for the PR, it looks like it needs some editing of the text for clarity but otherwise seems like helpful info.

2022-08-02 21:19 UTC, viktor-c commented
You are right with subpaths. Feel free to change the text, maybe somebody finds it useful someday :)

2022-08-31 17:46 UTC, shamoon requested changes
@viktor-c let me know if these changes work, just cleaned things up a bit.

2022-08-31 17:46 UTC, shamoon commented on docker/compose/docker-compose.env
> +#PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # leave a trailing slash, otherwise paperless will not start
```suggestion

# Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx
#PAPERLESS_FORCE_SCRIPT_NAME=/PATHPREFIX
#PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # trailing slash required
```

2022-08-31 17:46 UTC, shamoon commented on docs/configuration.rst
> +    When you do, change it for e.g. to /paperless/static/  Trailing slash!
```suggestion
    If you do change it, be sure to include the trailing slash.
```

2022-08-31 17:46 UTC, shamoon commented on docs/configuration.rst
> +      PAPERLESS_STATIC_URL=/paperlessngx/static/
```suggestion
    When hosting paperless behind a reverse proxy like Traefik or Nginx at a subpath e.g.
    example.com/paperlessngx you will also need to set ``PAPERLESS_FORCE_SCRIPT_NAME``
    (see above).
```

2022-08-31 20:30 UTC, viktor-c commented
One can read it better the way you wrote it, thanks!

2022-08-31 20:46 UTC, shamoon approved these changes, later dismissed

2022-08-31 21:01 UTC, shamoon approved these changes
Relevant tests are here because I rebased to `main`: https://github.com/paperless-ngx/paperless-ngx/runs/8122808155?check_suite_focus=true

2022-08-31 23:17 UTC, qcasey approved these changes
LGTM

2022-08-31 23:36 UTC, merged