Documentation:
paperless-ngx/paperless-ngx pull request #1733
Opened 2022-10-03 17:18 UTC by stumpylog

## Proposed change

This adds a few steps for helping users migrate from the deprecated LSIO image.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain) - docs

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2022-10-03 18:10 UTC, tribut requested changes
Thanks, very helpful! One small typo, otherwise lgtm!

2022-10-03 18:14 UTC, stumpylog commented on docs/setup.rst
> +        to step 3.
Thanks, did some re-numbering and missed that one.

2022-10-03 18:24 UTC, tribut approved these changes

2022-10-04 00:07 UTC, shamoon approved these changes
Thanks for doing this!

2022-10-04 00:07 UTC, merged