New dependencies added to the bare metal route install guide
paperless-ngx/paperless-ngx pull request #2220
Opened 2022-12-19 14:41 UTC by MrAlfabet

Added Celery and (I needed this even on earlier versions of paperless-ngx) default-libmysqlclient-dev

## Proposed change

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2022-12-19 15:27 UTC, shamoon commented
Thanks. `default-libmysqlclient-dev` Is already in both places

2022-12-19 15:28 UTC, shamoon requested changes

2022-12-19 15:28 UTC, shamoon commented on docs/setup.md
> +    - `default-libmysqlclient-dev` for DB communication
```suggestion
```

2022-12-19 15:28 UTC, shamoon commented on docs/setup.md
> +    python3 python3-pip python3-dev imagemagick fonts-liberation gnupg libpq-dev default-libmysqlclient-dev libmagic-dev mime-support libzbar0 poppler-utils default-libmysqlclient-dev celery
```suggestion
    python3 python3-pip python3-dev imagemagick fonts-liberation gnupg libpq-dev default-libmysqlclient-dev libmagic-dev mime-support libzbar0 poppler-utils celery
```

2022-12-19 15:31 UTC, shamoon approved these changes

2022-12-23 16:15 UTC, stumpylog commented
I don't think celery belongs here.  it should be installed via `pip`, not the system package manager.

2022-12-23 16:21 UTC, MrAlfabet commented
That's what I figured as well, but that didn't work for me.

On Fri, Dec 23, 2022, 17:15 Trenton H ***@***.***> wrote:

> I don't think celery belongs here. it should be installed via pip, not
> the system package manager.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/paperless-ngx/paperless-ngx/pull/2220#issuecomment-1364087467>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHYMS7GRGNEZWZOBDTL3WUDWOXF33ANCNFSM6AAAAAATDN63SE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-23 16:27 UTC, stumpylog commented
Probably something similar to step 11 then.  The actual executable location will vary depending on how and what installed it.  That is something which could be documented instead.

2022-12-24 02:48 UTC, stumpylog requested changes
If you'd like to add a note somewhere regarding the possible location of the celery executable, similar to the one about gunicorn, that could be useful for those using bare metal.

2022-12-24 16:21 UTC, shamoon commented
Thanks for clarifying I didn't notice. @MrAlfabet Please feel free to submit a new PR with that doc change

2022-12-24 16:21 UTC, closed without merging