Update setup.md
paperless-ngx/paperless-ngx pull request #2281
Opened 2022-12-30 23:36 UTC by natrius

Added some info to the baremetal installation and changed it up a bit for an hopefully easier installation experience

## Proposed change

Just flushed out the baremetal installation instructions so future installations hopefully will result in less questions like mine.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain)

Clarifications

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2022-12-31 01:03 UTC, shamoon requested changes
I mostly made grammar changes etc. I will let others comment on the content but looks OK to me

2022-12-31 01:03 UTC, shamoon commented on docs/setup.md
> +    using the browser from the same devices as paperless is installed.
```suggestion
    and pointing your browser to http://localhost:8000 if 
    accessing from the same devices on which paperless is installed.
```

2022-12-31 01:03 UTC, shamoon commented on docs/setup.md
> +        paperless-task-queue.service und paperless-scheduler.service
```suggestion
        paperless-task-queue.service and paperless-scheduler.service
```

2022-12-31 01:03 UTC, shamoon commented on docs/setup.md
> +    and copy the content to the
```suggestion
    and copy the contents to the 
```

2022-12-31 01:03 UTC, shamoon commented on docs/setup.md
> +    Optional: If you clone the git repo as it is, you also have to
```suggestion
    Optional: If you cloned the git repo, you will have to
```

2022-12-31 10:39 UTC, principis submitted a review, later dismissed
Looks good! I have a suggestion to help updating:

- Extract to a subdirectory, for example: `/opt/paperless/paperless-ngx-v1.11.2`
- Create a `paperless-latest` symlink to the extracted directory: `paperless-latest -> paperless-ngx-v1.11.2`
- Change all services: `WorkingDirectory=/opt/paperless/paperless-latest/src`

This allows for easy upgrading by just changing the symlink.

2022-12-31 11:29 UTC, natrius commented
Hm, that could be mentioned in an "Additional tips" or something like that but probably should not be included in the main. Additionally, the settings need to be changed and/or saved as well.

2022-12-31 16:26 UTC, shamoon commented
I squashed to 1 commit and ran `pre-commit` to fix the failing checks

2023-01-06 02:47 UTC, shamoon approved these changes
These look fine to me

2023-01-08 16:34 UTC, stumpylog approved these changes

2023-01-08 16:43 UTC, merged