Feature: Add a setting to disable creating archive files
paperless-ngx/paperless-ngx pull request #2732
Opened 2023-02-22 20:46 UTC by bdr99

## Proposed change
This PR adds a new `PAPERLESS_OCR_MODE` to completely disable the creation of archive files, while still performing OCR and storing the recognized text in the database. I personally have no desire for archive files with the OCR text embedded, I only want to be able to search the text in Paperless. I named the new option `skip_neverarchive` but I realize the names are a bit confusing and am open to suggestions for a better name.

This functionality was accidentally implemented in https://github.com/paperless-ngx/paperless-ngx/pull/1442 but was later reverted. In this PR I have re-implemented it under a separate option, using https://github.com/paperless-ngx/paperless-ngx/pull/1442 as a reference. https://github.com/paperless-ngx/paperless-ngx/pull/1829 says that the feature can be reintroduced if there is demand for it. At least one user has said they would appreciate this feature (https://github.com/paperless-ngx/paperless-ngx/issues/1678#issuecomment-1261775698), and I myself would find it extremely useful.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2023-02-23 23:07 UTC, stumpylog approved these changes

2023-02-23 23:22 UTC, merged

2023-02-23 23:24 UTC, jonaswinkler requested changes
I'd like you to consider the following.

Instead of skip_neverarchive, what about a separate configuration option "PAPLERESS_OCR_SKIP_ARCHIVE_FILE" or similar?

* Removes the need for skip_noarchive. I'd probably mark this as deprecated somehow, and keep it in the code for now.
* The feature can be combined with any of the OCR options, and it would make sense. One might want to use force since they have some weird documents that can't be properly processed otherwise, but don't care about the archive files just in the same way.

Am I missing something?

2023-02-24 00:12 UTC, shamoon commented
Ah, sorry for the crossed wires. I do like the idea of separating out the archive setting with its own variable. I suppose a PR that implements that idea could essentially revert this, unless we feel strongly about reverting it now?

2023-02-24 00:21 UTC, bdr99 commented
I also agree that the separate config option like @jonaswinkler described above would be better and less confusing, so feel free to revert this PR.

I'm going to try to work on implementing it, but it might take me a bit longer since I'm still new to this codebase.

2023-02-24 01:24 UTC, stumpylog commented
It would touch essentially the same files as done here, but also `paperless/settings.py`.

For deprecation, maybe inside `paperless/checks.py::settings_values_check`, append a `Warning` pointing to the new setting in place of `skip_noarchive`.

2023-02-24 03:53 UTC, bdr99 commented
Thanks for pointing me in the right direction @stumpylog. I opened https://github.com/paperless-ngx/paperless-ngx/pull/2743 with the new config setting.