Feature: global drag'n'drop
paperless-ngx/paperless-ngx pull request #283
Opened 2022-03-11 22:28 UTC by shamoon

This PR was inspired by #245 , it creates a "global" drag-and-drop feature on any page other than the dashboard (where there's still the upload box, I thought it was wise to keep that since this feature isnt really obvious). Essentially it stays out of the way but for users who want to upload it can be done from anywhere, I dont really see any downsides, do others?

I also fixed the fact that toasts dont currently fade in / out. Fading is nice.

Video below.

https://user-images.githubusercontent.com/4887959/157981154-038c6f51-df0b-4c0b-a31b-876ad5ee5cba.mov

2022-03-15 07:22 UTC, sukisoft commented
Hm, could be a nice feature, but i think this is not really obvious to the user, that it exists. Since one has to indicate a drop at first, and after that the possibility to drop is displayed. Yet i dont see a chance of displaying it properly, since the view is already "full of buttons and/or documents". Typical presentation would be a globally visible panel or something like that, which says "drop files to upload" or something like that.

For me personally i would not use that feature, i can live with the upload chooser on the dashboard.

2022-03-17 20:03 UTC, lippoliv requested changes

2022-03-17 21:07 UTC, shamoon commented on src-ui/src/app/app.component.html
> +            <h2>Drop files to begin upload</h2>
Thank you, great catch! How English-centric of me =)

2022-04-05 20:15 UTC, shamoon commented
Thanks, I fixed that and also fixed a random bug I found with the CSS spacing of the filter editor (literally it looks exactly the same just fixes a small overflow thing)

2022-04-05 20:19 UTC, qcasey approved these changes
Awesome, thank you! This is a very useful feature.

2022-04-05 20:20 UTC, shamoon commented
Sorry 1 thing! for FrankStrieter =)

2022-04-05 20:33 UTC, shamoon commented
Okey-dokey =)

2022-04-07 19:14 UTC, merged