Improvement to ASN barcode detection for small barcodes.
paperless-ngx/paperless-ngx pull request #3655
Opened 2023-06-21 21:05 UTC by bmachek

## Proposed change

My QR code labels weren't recognized during ASN barcode detection in paperless, as they seemed to be to small for pyzbar to detect them. I cannot use zxing, as I run paperless on arm64. Couldn't even test zxing, because I currently do not own a x86 device ;-)

I figured that converting the PDF pages with a dpi of 600 and then upscale the resulting image by 1.5 fixes my issue.

## Type of change

I added the ability to paperless to configure an upscale factor and the dpi used in the conversion.
Default values go to 1.0 upscale factor and dpi of 300, so nothing changes for users that are unaffected by this issue. The code won't try to upscale the image by 1.0, it skips the step.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2023-06-22 16:38 UTC, shamoon commented
Thanks for the PR.

Yea there have been issues with this in the past, eg [#2516](https://github.com/paperless-ngx/paperless-ngx/issues/2516). I don't use the barcode feature, nor have I spent much time with that part of our code. 

In general this looks OK to me but Im always a little hesitant to add more config options, we're sort of at config overload already. Since we dont track anything, we dont have a good way to track how many people want / would use / would benefit from something like this (also a thought to opening discussions before PRs). But I do appreciate the 'sane' defaults and that this would leave things as-is for existing users.

Perhaps other folks will have more thoughts.

One other thing is that we like to include testing of new code, so if you could add that, eg https://github.com/paperless-ngx/paperless-ngx/blob/dev/src/documents/tests/test_barcodes.py

2023-06-22 17:45 UTC, stumpylog commented
I'm alright with adding the settings.  Though I do know we're very, very configurable at this point.

2023-06-22 17:58 UTC, bmachek commented
Ok, thanks for the feedback.
@shamoon Will add some tests to test_barcodes.py soon.

2023-06-22 18:01 UTC, stumpylog requested changes

2023-06-24 05:55 UTC, bmachek commented on src/documents/barcodes.py
> +                if factor != 1.0:
Scaling by 1.0 didn't was already ruled out by the old code. In the new commit downscaling is also disabled, as I can't think of a use case.

2023-06-24 05:56 UTC, bmachek commented on docs/configuration.md
> +`PAPERLESS_CONSUMER_ASN_BARCODE_UPSCALE=<float>`
Rename both upscale and dpi variables accordingly.

2023-06-24 05:56 UTC, bmachek commented
> One other thing is that we like to include testing of new code, so if you could add that, eg https://github.com/paperless-ngx/paperless-ngx/blob/dev/src/documents/tests/test_barcodes.py

Added a new PDF in samples and wrote a pytest.

2023-06-24 06:00 UTC, shamoon commented
Thanks, I would perhaps include the before / after in that test (i.e. that it fails without the upscaling)

2023-06-25 04:40 UTC, bmachek commented
> Thanks, I would perhaps include the before / after in that test (i.e. that it fails without the upscaling)

Did that by writing another test, with default settings for dpi and upscale. Maybe this test will fail someday, when pyzbar gets better or zxing becomes default. But IMHO it's OK for now.

2023-06-25 13:49 UTC, shamoon commented on paperless.conf.example
The new vars should have their default values here

2023-06-25 13:50 UTC, shamoon commented on src/documents/tests/test_barcodes.py
> +        ?????
```suggestion
```

2023-06-25 13:51 UTC, shamoon commented on src/documents/tests/test_barcodes.py
> +        ?????
```suggestion
```

2023-06-25 16:02 UTC, bmachek commented
I made the requested changes.

The CI runs using ZXing for my pytest methods show that the results differ for negative test without upscaling.
ZXing doesn't seem to need upscaling or higher dpi to detect the small QR code in the test PDF.
This puts the functionality upscaling/dpi to the state of a workaround for the build issues of ZXing on aarch64.
So it maybe removed once ZXing settles its problems there.

2023-06-25 16:27 UTC, shamoon commented
Yea thats part of why I wanted the testing, theres a bit of overlapping 'workarounds' here (making both barcode libraries available itself is a sort of workaround).

Thanks, perhaps you can throw in a comment to the tests to explain the above a bit (for some future date). Otherwise, Im good with this, though I will leave final approval to the backend folks (the main person of which is currently AFK so there may be a small delay in finalizing this).

Thanks again

2023-06-27 15:49 UTC, stumpylog approved these changes
I'm good with the changes.  I'll leave it up the @shamoon if this merges to `dev` or if that happens a little later (after other bugfix releases)

2023-06-27 17:18 UTC, shamoon commented
Cheers all, thanks for all the work @bmachek

2023-06-27 17:18 UTC, merged