Added support for subdir as owner consumption
paperless-ngx/paperless-ngx pull request #4190
Opened 2023-09-15 21:56 UTC by andreheuer

## Proposed change

This PR should implement a first way to enable the consumption of a document from a consume folder supporting different document owners. If this functionality is enabled via a setting, the consumer checks if the first sub-folder of a document to consume is equal to an existing username. If so, the owner of the document will be set to this user. If not, the sub-folder name is ignored and the document will have no owner. In combination with the subfolder as tag feature, the first part of the folder is checked if it matches to a username and if so, it is ignored for the tagging. If a username does not match, the first subfolder is treated as a tag (as is).

Use case is e.g. to point the destination folder of a scanner to a user specific sub-folder.

Fixes #2177

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2023-09-15 22:52 UTC, stumpylog requested changes
Generally seems like a workable solution, some suggestions

2023-09-15 22:52 UTC, stumpylog commented on src/documents/management/commands/document_consumer.py
> +    Returns Owner ID or None
If this returns "or None", the typing should indicate that

2023-09-15 22:52 UTC, stumpylog commented on src/documents/management/commands/document_consumer.py
> +    owner_id = User.objects.get(username__iexact=path_parts[0]).pk
If the subfolder name doesn't exist, this raises `model.DoesNotExist`.  Consumption continues, but it's messy.  You should check [`exists`](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#django.db.models.query.QuerySet.exists) first

2023-09-15 22:52 UTC, stumpylog commented on src/documents/management/commands/document_consumer.py
> +def _owner_from_path(filepath) -> int:
In general, I feel like this and `_tags_from_path` could be combined.  There's duplication in particular the initial path parsing.  Returning a dataclass of tuple with the owner id (or none) and the list of tag ids (or none), depending on settings and matching

2023-09-15 22:52 UTC, stumpylog commented on src/documents/tests/test_consumer.py
> +    def testOverrideOwner(self):
Python conventions, per PEP8, are to use `snake_case`, not `camelCase`.  Since this is new, lets use that

2023-09-15 22:52 UTC, stumpylog commented on src/documents/tests/test_management_consumer.py
> +class TestConsumerOwner(DirectoriesMixin, ConsumerThreadMixin, TransactionTestCase):
Please add the given/when/then convention to provide some context for what each of these is trying to accomplish

2023-09-15 23:40 UTC, shamoon reviewed
Thanks, yea seems like a good simple solution for now (I have some grandiose other ideas). I added some small docs changes. 

My one question is why this requires `PAPERLESS_CONSUMER_RECURSIVE`? I mean, I understand from the programming perspective that it makes it easier but it feels to me as a user that it shouldn't be required, no? Like they're not related other than that they share some code here

2023-09-15 23:40 UTC, shamoon commented on docs/configuration.md
> +file. Paperless will not create a user that don't exist yet and the file will not have an owner.
```suggestion
file. Paperless will not create users that do not exist, instead the file will have no owner set.
```

2023-09-15 23:40 UTC, shamoon commented on docs/configuration.md
> +    their files in the their own folders. These folders won't be deleted.
```suggestion
```

2023-09-16 06:18 UTC, shamoon commented
Actually, you might want to hold off on working on this @andreheuer , we may have something a little bigger in the works that would replace this. Dont want you to put in more time unnecessarily. I'll let you know asap...

2023-09-16 10:25 UTC, andreheuer commented
Hi @shamoon and @stumpylog,
thank you for your instant feedback :-)
I will follow @shamoon suggestion and wait with further updates and corrections for now. Looking forward what is coming next!

2023-09-17 08:20 UTC, shamoon commented
Thanks again for the PR

See #4196 which actually covers this

2023-09-17 08:20 UTC, closed without merging