Documentation enhancement: add direct links for all config vars
paperless-ngx/paperless-ngx pull request #4237
Opened 2023-09-21 17:48 UTC by shamoon

## Proposed change

This one's also been bugging me for ages, just had to figure out the regex for find & replace =) The only other thing here is I'm hiding these from the sidebar because its so messy otherwise (lmk if anyone disagrees). Also makes search for these much better. I also took the opportunity to update all links to these to be 'direct' (I'll update the frontend UI links separately)

<img width="858" alt="Screenshot 2023-09-21 at 10 32 17 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/b49fad71-739d-4477-a697-6b44c9329c1c">

<img width="892" alt="Screenshot 2023-09-21 at 10 18 23 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/78ed789c-dbcc-42ea-9330-c14bbf28bf05">

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): docs enhancement

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2023-09-21 17:48 UTC, shamoon commented
Reminder: ci failure isn't 'real'

2023-09-21 23:34 UTC, stumpylog requested changes
Seems like a very handy change.  I'm seeing the USERMAP vars in the sidebar still:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/797416/24c08b4f-e57d-4da4-9a28-d9362459ed4e)

2023-09-22 00:17 UTC, shamoon commented
Ah, great catch thanks. Fixed!
<img width="359" alt="Screenshot 2023-09-21 at 5 16 17 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/22658175-7ff6-4de1-a0bb-3e5923247353">

2023-09-22 18:08 UTC, stumpylog approved these changes

2023-09-22 18:12 UTC, merged