Feature: password reset
paperless-ngx/paperless-ngx pull request #4289
Opened 2023-09-28 18:20 UTC by shamoon

## Proposed change

Seriously this is the last one from me for now. This implements a password reset page, really just using that which is built into Django and spiffing up the templates.  We could use the email server for other things down the road...

One thing I wasnt sure about, since it requires an smtp server I had the template hide the "Forgot your password?" link, its currently set to check `EMAIL_HOST` or `EMAIL_HOST_USER`, I figured there might actually be a situation where someones using a localhost for smtp.

Screenshots below.

<img width="476" alt="Screenshot 2023-09-28 at 10 55 56 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/3cdb632b-bb32-4842-b661-7893bd2db631">

<img width="504" alt="Screenshot 2023-09-28 at 10 56 09 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/4cf99a25-495e-45fe-90fb-a009a6dafa0e">

<img width="773" alt="Screenshot 2023-09-28 at 10 56 22 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/62670c02-2777-493b-bb83-9db6a565fec6">
<img width="528" alt="Screenshot 2023-09-28 at 10 57 05 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/d8ac5520-6f3f-4568-b212-8ae3d0951206">
<img width="467" alt="Screenshot 2023-09-28 at 10 57 25 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/5ff49c9e-5ecf-43a5-9e5b-47979debef46">

Fixes #3362
Fixes #4269

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2023-09-29 03:00 UTC, stumpylog requested changes
A couple little things.  Didn't attempt to create a server to fully test.  Curious too if there can be any sort of check the link was sent correctly?  Or settings validation so the smtp server is known to be configured correctly?

2023-09-29 03:00 UTC, stumpylog commented on docs/configuration.md
> +#### [`PAPERLESS_EMAIL_USER=<str>`](#PAPERLESS_EMAIL_USER) {#PAPERLESS_EMAIL_USER}
This name doesn't match the `settings.py` environment name.

2023-09-29 03:00 UTC, stumpylog commented on docs/configuration.md
> +#### [`PAPERLESS_EMAIL_PASSWORD=<str>`](#PAPERLESS_EMAIL_PASSWORD) {#PAPERLESS_EMAIL_PASSWORD}
Nor this one

2023-09-29 03:03 UTC, shamoon commented on docs/configuration.md
> +password. All of these options come from their similarly-named [Django settings](https://docs.djangoproject.com/en/1.8/ref/settings/#email-host)
ha thanks

2023-09-29 03:09 UTC, shamoon commented
Ah thanks, fixed those things (I swear I double-checked them, too much copypasta)

As for your qs:

- I dont know about the first part, again this comes straight from Django. I know if you try to send an email without a valid server you do get an [ugly] error in the browser.
- Validating the server I guess would mean actually connecting to it? Im not sure, is that something you would do in system checks? I dont really know how you would do it here? As you can see, we dont explicitly create these views, etc. we're just using templates for the built-in views, I think.

Totally open if you see how to do either, of course

2023-09-29 05:01 UTC, shamoon commented
@stumpylog I added a system check for this, let me know what you think, no big deal to revert that part if youre not into it.

2023-09-29 16:43 UTC, stumpylog commented
I think if there's a big exception of some sort in the logs, that is enough.  The thing with the checks, they run a lot.  So if a user wants to export, but their SMTP server is having problems, they couldn't as that check would fail.  And it's network calls, which could be pretty slow.

2023-09-29 23:33 UTC, shamoon commented
The exception isnt in the logs, its in the browser, e.g.:

2023-09-29 23:35 UTC, shamoon commented
Sorry, accidentally sent comment. The exception is in the logs and in the browser, e.g.:
<img width="1033" alt="Screenshot 2023-09-29 at 4 34 44 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/67d1792f-40f4-487e-9e10-e8765e2e2e88">

I reverted the system check 👍

2023-09-30 00:03 UTC, stumpylog commented
Curious, with `PAPERLESS_EMAIL_HOST_USER` defined, I get the link.  But no error, despite having no server configured that I know of.

Also (and I should have thought of this before), who's password does this reset?  Does it lookup via email the user?

2023-09-30 00:22 UTC, shamoon commented
Sorry if Im misunderstanding. You only get the error after trying to submit the reset. If either of those are set it shows you the link, the idea being "this instance looks like it setup email" (but not validated).

And yea, uses email

2023-09-30 00:23 UTC, shamoon commented
Edit: error is after (trying to) sending the email, not the reset pw

2023-09-30 00:33 UTC, stumpylog commented
It must be from putting in an email which doesn't have a user mapped to it.  Django policy in that case is no error messages, based on the [note here](https://docs.djangoproject.com/en/4.2/topics/auth/default/#django.contrib.auth.views.PasswordResetView)

2023-09-30 00:36 UTC, shamoon commented
Ah, yea now I get it. Yea thats a common thing on login forms I think, dont tell the attempter why it failed ("username not found", "wrong password", etc. all are just giving potential 'hints' to attackers)

2023-10-01 01:17 UTC, stumpylog approved these changes

2023-10-01 01:17 UTC, merged