barcode logic: strip non-numeric characters from detected ASN string
paperless-ngx/paperless-ngx pull request #4379
Opened 2023-10-15 17:02 UTC by queaker

## Proposed change

legacy barcodes exist which still contain characters after the number the current logic did not truncate them. instead, int() was called from the remaining string. this does not work in this case. it is therefore sufficient to continue processing numeric characters.

![Bildschirmfoto 2023-10-15 um 18 56 33](https://github.com/paperless-ngx/paperless-ngx/assets/4228208/c9a960ff-933f-4952-a295-1b0ac1c09bed)
(containing *A*<ASN>* in the content of the barcode)

I have not found anything about the behavior of the function in the documentation. However, I would expect the behavior to be as it is after the change. I don't know if this is a bug-fix or a new feature.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [X] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [X] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [X] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [X] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [X] I have made corresponding changes to the documentation as needed.
- [X] I have checked my modifications for any breaking changes.

2023-10-15 19:07 UTC, shamoon commented
This seems a bit odd. Where did that barcode come from, as in, did you make it? It's not that this seems like a big change but wouldn't we expect users to be creating ASN barcodes correctly?

And in general, ASN barcodes are supposed to be of the format `ASN00123` with the prefix being [configurable](https://docs.paperless-ngx.com/configuration/#PAPERLESS_CONSUMER_ASN_BARCODE_PREFIX).

2023-10-16 07:59 UTC, queaker commented
> This seems a bit odd. Where did that barcode come from, as in, did you make it? 

the format of the barcodes comes from a former document management - which i migrated from al long time ago. so far i recognize the barcodes with a post-consume-script. now that paperless-ngx has learned to recognize the barcodes, i would want to use the integrated functions. I still have 500 stickers that I would like to use up.

2023-10-16 14:24 UTC, shamoon commented
> the format of the barcodes comes from a former document management

Ah, yes that explains it. So your prefix could be set to `*A*` but the last * remains. In general this seems OK to me, obviously it's a small change but I wanted to ensure it wouldn't cause unintended consequences. For example if someone uses a non-number character in their ASN it will now 'silently' succeed.

I'll hold off on merging pending anything from the backend team

2023-10-16 14:25 UTC, shamoon requested changes
You need to run our linter

2023-10-16 14:26 UTC, shamoon commented on src/documents/barcodes.py
> +            asn_text = re.sub('[^0-9]','', asn_text)
```suggestion
            asn_text = re.sub('[^0-9]',"", asn_text)
```

2023-10-16 14:34 UTC, shamoon approved these changes

2023-10-17 02:56 UTC, stumpylog approved these changes
Seems like a bit of a special case, but I don't see it breaking anything

2023-10-17 03:44 UTC, merged