Feature: update user profile
paperless-ngx/paperless-ngx pull request #4678
Opened 2023-11-26 15:57 UTC by shamoon

## Proposed change

Allows a user to change (only their) password, email, name. Also allows retrieving the token from the frontend, a pet peeve of mine.

<img width="521" alt="Screenshot 2023-11-26 at 7 41 17 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/c5528239-77d7-43fe-bc8b-226353bcc6f9">

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/e141407f-f941-443b-a19b-43c496df20a1

Fixes #3230

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2023-11-30 23:15 UTC, stumpylog requested changes
Still need to actually test, but had a though about the backend anyway

2023-11-30 23:35 UTC, shamoon commented on src/documents/tests/test_api.py
> +class TestApiProfile(DirectoriesMixin, APITestCase):
Yea it is, hard to find stuff sometimes. Maybe `test_api_profile`?

2023-11-30 23:38 UTC, stumpylog commented on src/documents/tests/test_api.py
> +class TestApiProfile(DirectoriesMixin, APITestCase):
Yeah, I was going to get around to it sometime, but I planned to keep things as `test_api_*.py` so they stay grouped

2023-11-30 23:51 UTC, shamoon commented
Let me know if good with the changes, I honestly think its not possible that the request doesnt have 'user' so I left it off, but let me know if Im wrong about that (and if so, how to write a test that would repro it). I did add test for logged out to confirm the 401

2023-12-01 01:51 UTC, stumpylog commented
One thing I'm seeing, after the logout from changing the password, the page after i log back in is consistently a 404.  I can't tell from the network tools what it's trying to load though, nothing there is returning a 404

2023-12-01 02:14 UTC, shamoon commented
Ah, this reminds me I had to include a manual logout for the users component when the pw changes, I bet that'll do it. Good catch, thanks.

2023-12-01 02:56 UTC, shamoon commented
Annoying thing about my testing setup is it isnt really good for testing that kinda stuff, I'll double-check but this should now log you out just like under 'users & groups'

2023-12-01 04:11 UTC, shamoon commented
Actually it turns out that issue applies to the other (current) way to change a password too. And recreating it is very easy, if you go to `/accounts/logout/?next=/accounts/login/` (which is what this currently does) it'll happen. The solution seems simple enough which is to change it to `/accounts/logout/?next=/accounts/login/?next=/` which, though it looks wrong, seems ok. Basically its https://stackoverflow.com/questions/13186693/why-second-user-login-redirects-me-to-accounts-profile-url-in-django

Also fixed another small thing I noticed, hopefully this should be good now.

2023-12-02 16:12 UTC, stumpylog approved these changes
Yep, redirecting works great now

2023-12-02 16:26 UTC, merged