Enhancement: shared icon
paperless-ngx/paperless-ngx pull request #4859
Opened 2023-12-06 17:26 UTC by shamoon

## Proposed change

Small QoL enhancement. A few notes (I know seems like a lot for a small thing...):

- In some ways I think its a little weird to have the word 'Shared' on the small card, in other words it feels like it could be just the icon but this is much more consistent with how all the other little icons work, including for example the icon that shows when a document is owned by someone else (#3309). But welcome any other thoughts
    - We may need to consider limiting or allowing configuration of which things to show especially on the small cards. But given that this wouldn't change the current potential max (since you'd never have this + the owner icon by definition).
- Adds a `is_shared` field to docs. I dont think theres any performance penalty for this that I can notice.
- There is a sorta-related FR for being able to filter these: #3493 but honestly I didnt know how to do that because the logic (as you can see here) comes from an un-related db table. Again, it's separate, but just mentioning.

<img width="239" alt="Screenshot 2023-12-06 at 9 17 58 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/70152b7d-d1b7-40a1-aaa8-460b53ed7e0c">
<img width="385" alt="Screenshot 2023-12-06 at 9 18 07 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/f2e0b724-892a-498e-8531-008ff7db545b">

Fixes #4359 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2023-12-09 19:08 UTC, shamoon commented
Ok! I managed to figure out the 'shared by me' filter with a (sorta complex) annotation query. As with all backend stuff, appreciate any feedback and hopefully I didnt miss anything big.

Note that the filter var is implemented as `shared_by__id=X` because I needed a way to retrieve the user, it does not violate permissions, i.e. if a non-superuser runs that with someone else's ID they still cant see documents that aren't shared with them.

Also, I noticed that we didnt add a db migration for the custom fields filtering, so that is now included here.

Obviously this is a bigger PR now, no rush

2023-12-19 16:02 UTC, stumpylog requested changes

2023-12-19 16:04 UTC, shamoon commented on src/documents/tests/test_api_permissions.py
> +        self.assertEqual(
Thanks, got it!

2023-12-19 20:38 UTC, stumpylog approved these changes

2023-12-19 20:45 UTC, merged