Merging Non-Trivial PRs
paperless-ngx/paperless-ngx pull request #53
Opened 2022-02-15 18:59 UTC by qcasey

## Why

Our community/organization process for reviewing and merging PRs should be documented. Both for people submitting changes and those reviewing them. This ensures a standard is met for Paperless and that several members can attest to that quality. 

## Future updates

This updates `CONTRIBUTING.md`, but other contribution instructions are also found in [contributing.rst](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docs/contributing.rst) and [extending.rst](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docs/extending.rst). Maybe all 3 should be consolidated?

## Feedback

See here for the manifesto: https://github.com/paperless-ngx/paperless-ngx/blob/de9fbd48df1274c907b816914342764dbcb4291b/CONTRIBUTING.md?plain=1#L34-L57

Are there any steps to add/modify?

2022-02-15 19:04 UTC, shamoon commented
This is great I think. Is there a way to actually mark PRs as non-trivial? A label or something? And does that actually change review requirements or thats just for us to be aware?

2022-02-15 19:06 UTC, qcasey commented
I'd like it to actually change review requirements! I'll look into that. For now let's assume it's just to be aware.

2022-02-15 19:32 UTC, dblitt commented
I agree that having three related files is redundant. So long as we are still using the docs folder/readthedocs as our primary documentation store, perhaps we should just put a link to the proper readthedocs page in CONTRIBUTING.md instead of trying to synchronizing the two? Vice versa would also work, I don't have a strong preference.

2022-02-15 22:03 UTC, bauerj requested changes
Brilliant, thanks! I found some minor issues.

2022-02-15 22:07 UTC, bauerj commented
Would it make sense to add a GitHub Action that implements this?

With some more specific criteria, it could check if a new PR is trivial or not, apply a label, write a text and notify the right team. This would make the process more transparent for PR authors.

2022-02-15 22:11 UTC, qcasey commented
Thank you, updated. 

> With some more specific criteria, it could check if a new PR is trivial or not, apply a label, write a text and notify the right team. This would make the process more transparent for PR authors.

Yes that would be very useful

2022-02-15 22:59 UTC, apeltzer commented
We could also set up branch protection requiring:

- CI to pass
- 2 reviews

And open a separate issue for GHA setup.

2022-02-17 01:52 UTC, qcasey commented
> We could also set up branch protection requiring...

As of now Branch Protection requires 1 approval for merges into dev, 2 approvals for merges into master. Should there eventually be 2 on both?

2022-02-17 16:05 UTC, bauerj approved these changes

2022-02-17 16:05 UTC, merged

2022-02-17 16:06 UTC, bauerj commented
Right, the process as outlined in the document seems good to me 👍