docs: update celery monitoring docker usage
paperless-ngx/paperless-ngx pull request #5484
Opened 2024-01-21 09:15 UTC by Tooa

## Proposed change

Hi :wave: ,

this MR updates the celery monitoring docker usage in the advanced section of the paperless-ngx documentation. 

Let me know if you want anything changed.

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2024-01-21 14:29 UTC, shamoon requested changes

2024-01-21 14:29 UTC, shamoon commented on docs/advanced_usage.md
> +3. Start Flower by the container.
```suggestion
```

this line doesn’t really make sense (I mean grammatically) and seems sort of obvious I think. i would just remove it.

2024-01-21 14:29 UTC, shamoon commented on docs/advanced_usage.md
> +      - PAPERLESS_ENABLE_FLOWER # (3)!
```suggestion
      - PAPERLESS_ENABLE_FLOWER
```

2024-01-21 14:29 UTC, shamoon commented on docs/advanced_usage.md
>  To configure Flower further, create a `flowerconfig.py` and
```suggestion
Flower can be enabled with the setting [PAPERLESS_ENABLE_FLOWER](configuration/#PAPERLESS_ENABLE_FLOWER).
To configure Flower further, create a `flowerconfig.py` and
```

2024-01-21 14:29 UTC, shamoon commented on docs/advanced_usage.md
> +2. Flower runs by default on port 5555, but this can be configured.
```suggestion
2. By default, Flower runs on port 5555, but this can be configured.
```

2024-01-21 21:29 UTC, Tooa commented
Thanks for taking a look! I added your suggestions - all seem very reasonable. Feel free to squash and merge if nothing else is left open.

2024-01-22 00:10 UTC, shamoon approved these changes
Thanks

2024-01-22 00:17 UTC, merged