Respect cropbox for thumbnail generation
paperless-ngx/paperless-ngx pull request #5531
Opened 2024-01-24 16:37 UTC by henningBunk

## Proposed change

Use the `convert` argument `-define pdf:use-cropbox=true` when generating thumbnails. 

Some pdfs may have a cropbox. This is a feature to tell the pdf viewer to only display a certain page area. Until now thumbnail generation ignores this setting and renders the whole page. With this argument only the cropped area is used for the thumbnail generation.

| before         | after     |
|--------------|-----------|
| ![Screenshot 2024-01-23 205854](https://github.com/paperless-ngx/paperless-ngx/assets/14870695/3caddd95-ee05-48dc-9110-e4e92fccbf6d) | ![Screenshot 2024-01-24 015756](https://github.com/paperless-ngx/paperless-ngx/assets/14870695/05e4207c-faf2-4040-acfc-9a2f2905fed6)|

To test it I created this pdf file which uses a cropbox. The text `This should be visible!` should be big and centered. [cropbox_test.pdf](https://github.com/paperless-ngx/paperless-ngx/files/14041141/cropbox_test.pdf)

Closes #5518 

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [x] Other. Please explain: Don't know what to chose here. To me, the current behaviour feels like a bug and this would be a fix. But in the discussion it was also proposed that this would be a breaking changee.

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] ~~If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.~~ Out of my technical knowledge.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~ I don' think it's needed.
- [x] I have checked my modifications for any breaking changes.

2024-01-24 18:46 UTC, stumpylog requested changes

2024-01-24 18:47 UTC, stumpylog commented
In general, I don't think this would be a breaking change.  I'm doubtful most PDFs include a cropbox anyway

2024-01-31 18:19 UTC, henningBunk commented on src/documents/parsers.py
> +    define=None,
Sorry for the delay and thanks for the feedback. Implemented the changes, tested it again via docker and run the pytests.

2024-02-01 19:17 UTC, stumpylog approved these changes

2024-02-01 19:25 UTC, merged