Update administration.md
paperless-ngx/paperless-ngx pull request #5533
Opened 2024-01-24 17:53 UTC by gothicVI

## Proposed change

A backup via, e.g., `docker compose exec -T webserver document_exporter ../export` requires the webserver to still be running. We must not shutdown before that.

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2024-01-24 18:26 UTC, shamoon requested changes
I think that comment is meant to suggest that paperless is not performing any tasks (consumption, etc), if you wouldn't mind changing this PR to correct the wording as such. Also if youre not using docker it would still be accurate.

2024-01-24 18:59 UTC, gothicVI commented
> I think that comment is meant to suggest that paperless is not performing any tasks (consumption, etc), if you wouldn't mind changing this PR to correct the wording as such. 

Done :smile: 

> Also if youre not using docker it would still be accurate.

True, however, the change happens in the `### Docker Route {#docker-updating}` subsection so I'd argue that's not an issue here.

2024-01-24 19:09 UTC, shamoon approved these changes

2024-01-24 19:09 UTC, shamoon commented
> True, however, the change happens in the `### Docker Route {#docker-updating}` subsection so I'd argue that's not an issue here.

Ah, yea true =)

2024-01-25 21:21 UTC, stumpylog approved these changes

2024-01-25 21:21 UTC, merged