Enhancement: bulk delete objects
paperless-ngx/paperless-ngx pull request #5688
Opened 2024-02-08 06:53 UTC by shamoon

## Proposed change

Sneak another one in. This feels like a thing we ought to have and works like on might expect. 

I renamed the API endpoint to `bulk_edit_objects` to make it more generic (now requires an `operation` parameter), so this is breaking for the API, hence api version increment.

<img width="1840" alt="Screenshot 2024-02-07 at 10 23 02 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/e33f4ea3-db9a-4db8-a15a-a919bb7c383d">

Closes #2284

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [x] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2024-02-08 17:52 UTC, stumpylog requested changes
Just a little tweak

2024-02-08 17:56 UTC, shamoon commented on src/documents/serialisers.py
> +            permissions = attrs["permissions"] if "permissions" in attrs else None
Got it, you were right once I rebased. Should be sorted, thanks!

2024-02-08 18:13 UTC, stumpylog approved these changes

2024-02-08 18:13 UTC, merged

2024-02-08 18:13 UTC, stumpylog commented
This might show up and two headings in the changelog, breaking and feature

2024-02-08 18:18 UTC, shamoon commented
Yea, is that ok in this case (as opposed to when it puts things in fix + feature)?

2024-02-08 18:32 UTC, stumpylog commented
Yeah, just kind of an FYI in case you wanted to adjust the labels

2024-02-24 20:15 UTC, hannibal85 commented
Hi @shamoon 
With current paperless-ngx 2.5.3 i have mis-behaviour of permissions.
Not really sure if this is really related to this PR as I never tried permissions with previous versions but I think so.

Situation:
I have a restricted user that only is allowed to show correspondents, tags, etc. but has no permissions to create, edit, delete
![image](https://github.com/paperless-ngx/paperless-ngx/assets/16479725/d079c4fc-bc24-410a-aaf9-e3a2da9263f7)

This user can not edit or delete single objects (as expected) but can use bulk delete and also change permissions via bulk edit.
![image](https://github.com/paperless-ngx/paperless-ngx/assets/16479725/f39b8cd6-1777-4287-94e6-fcee51ffdfc4)

2024-02-24 23:19 UTC, shamoon commented
> Hi @shamoon With current paperless-ngx 2.5.3 i have mis-behaviour of permissions. Not really sure if this is really related to this PR as I never tried permissions with previous versions but I think so.

Yes, thanks. See https://github.com/paperless-ngx/paperless-ngx/pull/5888

2024-02-25 07:04 UTC, hannibal85 commented
Thanks for the quick fix. Awesome work.