Feature: system status
paperless-ngx/paperless-ngx pull request #5743
Opened 2024-02-12 21:17 UTC by shamoon

## Proposed change

Seems like a useful little thing to have but unobtrusive otherwise. Im a little unsure about some of the methods for testing environment etc. but I got expected results when testing myself. Would be good to check that, false-positive errors would suck. 

Im open to more stuff here but didnt want to go too crazy (biggest one I considered but didnt was CPU/MEM kinda stuff).

<img width="1150" alt="Screenshot 2024-02-12 at 10 43 33 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/8f781454-6c2f-4824-af23-6aa948c9580f">
<img width="1152" alt="Screenshot 2024-02-12 at 1 15 01 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/31dba7c2-f275-41ee-8693-81f463159eea">
<img width="220" alt="Screenshot 2024-02-12 at 11 17 54 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/35f0e362-168f-4687-9f06-54060d8f8fd0">
<img width="210" alt="Screenshot 2024-02-12 at 11 18 48 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/c58c7103-9c0c-4ac0-8f2c-0e44daec2060">

Closes #5704 

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2024-02-12 21:25 UTC, shamoon commented
No rush on this

2024-02-13 15:39 UTC, noseshimself commented
If possible, please add the underlying file system, too.

2024-02-13 16:04 UTC, shamoon commented
It displays the info for the `/media/` storage.

2024-02-13 16:47 UTC, shamoon commented
Given most users are running inside docker I’m not sure how much of that is available to the python backend. In general the goal here is not to be a comprehensive stack inspector, just to alert the user of potential problems and the basics of their setup.

2024-02-13 21:23 UTC, Gendra13 commented
Would it make sense to include the status of the search index as well as the classification model?

2024-02-14 03:30 UTC, shamoon commented
> Would it make sense to include the status of the search index as well as the classification model?

Great idea

<img width="1152" alt="Screenshot 2024-02-13 at 4 40 39 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/dd694c2d-f815-42fe-b4c1-785f59fea7ff">
<img width="1155" alt="Screenshot 2024-02-13 at 4 40 30 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/ed8c75a7-8581-4004-aa4d-1b1c931f6f37">

2024-03-04 04:22 UTC, stumpylog requested changes

2024-03-04 04:22 UTC, stumpylog commented on src/documents/tests/test_api_status.py
> +    def test_system_status(self):
Nit: The little comment for tests

2024-03-04 05:47 UTC, shamoon commented on src/documents/views.py
> +        redis_url = settings._CELERY_REDIS_URL
Take your word on that!

2024-03-04 05:56 UTC, shamoon commented
Thanks stumpy. Yea my thing with this one is a little unsure how it will behave in some environments (looking at you nixOS), may need some iterating...

2024-03-04 17:23 UTC, stumpylog commented on src/documents/views.py
> +        redis_url = settings._CELERY_REDIS_URL
It's confusing/annoying that celery decided to make their own URL scheme

2024-03-04 17:26 UTC, stumpylog approved these changes

2024-03-04 17:26 UTC, merged