Documentation: improve permissions docs
paperless-ngx/paperless-ngx pull request #6046
Opened 2024-03-07 18:29 UTC by shamoon

## Proposed change

It is something else to maintain but hopefully useful. LMK if I missed anything of course.

Closes #documented

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2024-03-08 20:13 UTC, stumpylog requested changes
Thanks for the cleanup, couple suggestions

2024-03-08 20:13 UTC, stumpylog commented on docs/usage.md
> +Documents consumed via the consumption directory or directly to the API do not have an owner or
Doesn't the API take the request user as the owner?

https://github.com/paperless-ngx/paperless-ngx/blob/025001499d27723f83d43dc75ff2f4705b2369b8/src/documents/views.py#L957

2024-03-08 20:13 UTC, stumpylog commented on docs/usage.md
> +| User          | Grants global permissions to add, edit, delete or view Groups.
This says Groups, but should be Users

2024-03-09 00:21 UTC, shamoon commented
Thanks stumpy, great catch x2. Let me know if you notice anything else

2024-03-11 15:15 UTC, stumpylog approved these changes

2024-03-11 15:20 UTC, merged