Fix bulk edit url in docs
paperless-ngx/paperless-ngx pull request #6057
Opened 2024-03-08 18:56 UTC by fidothe

## Proposed change

Fix error in the URL for document bulk edits in the API docs; clarify that the `delete` operation still requires the parameters key to be present in the JSON body, even though it should contain an empty JSON object.

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ X ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ X ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ X ] I have made corresponding changes to the documentation as needed.
- [ X ] I have checked my modifications for any breaking changes.

2024-03-09 00:34 UTC, shamoon requested changes
I need to double-check about the delete thing. if that’s true (I’m guessing you tested it and the front end does do that) then either it should be changed (not here), but if not then it applies to every endpoint that doesn’t require any params, not just delete

2024-03-09 02:53 UTC, shamoon commented
As long as there are no issues with it, #6059 should make the delete endpoint work more as expected so if you dont mind reverting that change here. Thanks

2024-03-09 23:10 UTC, shamoon approved these changes

2024-03-09 23:11 UTC, merged

2024-03-10 18:39 UTC, fidothe commented
Oh hey, you got to it before I could 😄.  I wondered about the empty parameters thing, which I why I made it a separate commit...