Documentation: document_importer does not directly support zip archives
paperless-ngx/paperless-ngx pull request #6209
Opened 2024-03-27 22:37 UTC by biocoder-frodo

## Proposed change

Follow up to discussion https://github.com/paperless-ngx/paperless-ngx/discussions/6178#discussioncomment-8918600
In this discussion I mentioned I would try having two homes for my paperless database and some experimentation led me to the following errors
```
biocoder@diskstation:~$ sudo docker exec -it paperless-ngx document_importer ..                                                                                                                                                             /export
Password:
Found file 0000001.pdf, this might indicate a non-empty installation
Found file 0000001.pdf, this might indicate a non-empty installation
Found existing user(s), this might indicate a non-empty installation
Found existing documents(s), this might indicate a non-empty installation
CommandError: That directory doesn't appear to contain a manifest.json file.
biocoder@diskstation:~$ sudo docker exec -it paperless-ngx document_importer ..                                                                                                                                                             /export
Found file 0000001.pdf, this might indicate a non-empty installation
Found file 0000001.pdf, this might indicate a non-empty installation
Found existing user(s), this might indicate a non-empty installation
Found existing documents(s), this might indicate a non-empty installation
Checking the manifest
Installed 198 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Copy files into paperless...
 50%|██████████████████████▌                      | 3/6 [00:00<00:00,  6.94it/s]
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.                                                                                                                                                             py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.                                                                                                                                                             py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py",                                                                                                                                                              line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py",                                                                                                                                                              line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_importer.p                                                                                                                                                             y", line 182, in handle
    self._import_files_from_manifest(options["no_progress_bar"])
  File "/usr/src/paperless/src/documents/management/commands/document_importer.p                                                                                                                                                             y", line 278, in _import_files_from_manifest
    raise FileExistsError(document.source_path)
FileExistsError: /usr/src/paperless/media/documents/originals/0000002.pdf
biocoder@diskstation:~$
```
The first invocation of document_importer failed harmlessly, I followed the documentation literally and sort of expected a ZIP file to be opened automatically. 
The second invocation of document_importer failed because I attempted to restore 6 items from my workstation instance in the instance on my NAS that still had 1 other item in its database. The result was that item 1 kept the original scan but got its metadata from the first item scanned on my workstation. One of the other 6 items had no scans attached to it anymore.
Figuring that changing the "non-empty installation" warning into a fatal error might break someones workflow(s), I thought "let's also update the documentation for that as well"

I also added some notes of additional steps I had to do in my Ubuntu WSL installation on Windows to serve the documentation as I was preparing this PR.
## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2024-03-27 23:39 UTC, stumpylog commented
* The note that zip archives are not imported directly is generally fine, but seems superflous.  The documentation already states the importer acts on a directory and a zip file is not a directory
* The note for a clean slate is mostly fine.  I don't think there should be mention of "taking great care".  That case is simply not supported, only a clean slate is, just as the importer will warn about
* The note added to the development page is wrong, the libraries are already development dependencies and will be installed with `pipenv sync --dev`.  No one should manually install Python libraries.  Please remove it.

2024-03-28 00:07 UTC, biocoder-frodo commented
Reverted the development.md change.

> The document importer takes the _export produced_ by the [Document exporter](https://docs.paperless-ngx.com/administration/#exporter) and imports it into paperless.
> The importer works just like the exporter. You point it at a directory, and the script does the rest of the work

Emphasis mine, but this reads to me as any output from the exporter will be happily accepted by the importer :)

The paragraph about the expected clean slate, the warning messages that are given are not really a warning messages, because you cannot stop the process anymore once they are given? If it is really unsupported, then maybe outright refusing to continue would be a better option.

2024-03-28 00:12 UTC, shamoon requested changes
Agree with stumpy on all those, and in general this should be way shorter. I made some suggestions.

Thanks

2024-03-28 00:12 UTC, shamoon commented on docs/administration.md
> +
```suggestion
Note that .zip files (as can be generated from the exporter) are not supported.

```

Everything else here is extraneous, repeating the cli flags, mentioning the data and manifest, etc.

2024-03-28 00:12 UTC, shamoon commented on docs/administration.md
> +	items into a paperless instance that is not completely empty.
```suggestion
!!! warning
    The importer should be run against a completely empty installation (database and directories) of Paperless-ngx.
```

Same theme as above.

2024-03-28 00:14 UTC, shamoon commented
> > The document importer takes the _export produced_ by the [Document exporter](https://docs.paperless-ngx.com/administration/#exporter) and imports it into paperless.
> > The importer works just like the exporter. You point it at a directory, and the script does the rest of the work
> 
> Emphasis mine, but this reads to me as any output from the exporter will be happily accepted by the importer :)

You could also probably clear this point up by changing that sentence to "The document importer takes the exported files (not a .zip file) produced by the [Document exporter](https://docs.paperless-ngx.com/administration/#exporter) and imports it into paperless."

2024-03-28 02:11 UTC, stumpylog commented
Looks good to me now, thanks, just need to get the linting sorted

2024-03-28 02:36 UTC, shamoon approved these changes

2024-03-28 02:53 UTC, stumpylog approved these changes

2024-03-28 02:53 UTC, merged