Add option to delete original documents after merge
paperless-ngx/paperless-ngx pull request #6935
Opened 2024-06-07 09:14 UTC by theomega

## Proposed change
Adds the possibility to delete the original documents after merging them. This option is disabled per default in the UI. 
As choosing this option deletes the original documents, the operation is only available to the owner of the documents (similar to the delete operation). This is different from the "non deleting" merge operation, that is available to every user that was allowed to change all the original documents.

Screenshot of the modified Confirm Modal for the merge:
<img width="865" alt="Screenshot 2024-06-07 at 11 10 43" src="https://github.com/paperless-ngx/paperless-ngx/assets/905977/655480ef-390e-4de0-b67d-b5bb6cc76d57">

I'm marking this as a draft due to two short comings (most likely more to be found by others), I'm very open for input:
- [ ] We should hide the "Delete Originals" checkbox in the Modal if the user is not the owner of all the documents. Otherwise, the API request will fail which is not nice. I'm unsure how to do this.
- [ ] I'm unsure how to write some good tests for this, both UI and backend. 

Closes partly #6446. I'm happy to provide the same functionality for the splitting functionality in a second PR.

## Type of change
- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:
- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2024-06-07 14:02 UTC, shamoon requested changes
1. I see no reason to make merge_and_delete a separate method, it seems you only did that because you weren’t sure how to check permissions (I agree delete originals should require ownership), but I think it should be changed to just be an option for merge.
2. More importantly, what makes this PR a little challenging is that delete should only happen if the documents are successfully merged, which of course is done asynchronously so it needs to be queued with celery. As is, this will delete the originals even if merge just completely fails, which wouldn’t be great
3. Also, split should be included here, the changes will be incredibly similar
4. Considering the above and no testing, I’ll mark this as a draft.

2024-06-07 14:07 UTC, shamoon commented
Also, split should be included here, the changes will be incredibly similar

2024-06-07 14:18 UTC, theomega commented
> I see no reason to make merge_and_delete a separate method, it seems you only did that because you weren’t sure how to check permissions (I agree delete originals should require ownership), but I think it should be changed to just be an option for merge.
As stated in the PR, this is intentional and not due to lack of knowledge. As stated above, I can change this to make this a parameter, but then we need to inspect the parameters in the `BulkEditView` `post` method, including a special handling for the `merge` bulk action. If you are fine with this approach, I'm happy to adapt the PR.

> More importantly, what makes this PR a little challenging is that delete should only happen if the documents are successfully merged, which of course is done asynchronously so it needs to be queued with celery. 
Are you sure about this? The `merge` method in the code does the merging synchronous to the API-Request and only does the consuming then via celery, if I read the code correctly. Otherwise also my code would not work (deleting would happen before merging), and it actually does, I tested it thoroughly.

> Also, split should be included here, the changes will be incredibly similar
Fine, but let's agree on this implementation first, otherwise we have double work.

> ... and no testing
Let me know which testing you are missing, happy to do it. As mentioned above, this is thoroughly tested and there is a test-case for the bulk-edit function.

2024-06-07 14:47 UTC, shamoon commented
To clarify, I mean that I think the delete operation should only happen after successful consumption of the merged doc, which yes, is queued and performed synchronously

Seems like you’ve sorted out the testing with maybe one line remaining for coverage.

And yes, you can wait until this stuff is sorted out before adding split

2024-06-07 14:48 UTC, shamoon commented
Stinking autocorrect! *A*synchronously

2024-06-07 15:37 UTC, theomega commented
Thanks for the feedback.

I changed the implementation and made `delete_originals` a parameter to the `merge` function on both API and code in the backend. The `merge_and_delete_originals` method is gone. Permission checks are adapted (as mentioned by me, this became more complex). Frontend is adapted as well and test coverage is achieved for all border cases (Code-Coverage here in the PR does not update due to an error in the CI/CD: "Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 1309 seconds.")

> To clarify, I mean that I think the delete operation should only happen after successful consumption of the merged doc, which yes, is queued and performed asynchronously
I'm unsure here how to do this. We would need an additional celery task for the deletion and somehow chain it with the consumption (so make one celery task depend on the other). I'm really unsure if it is worth the effort and the complexity. A big challenge will be writing good tests for this. I personally don't see a big value in it, the deletion only happens after a successful merge.

I don't know how to pull this off. If you insist on this, then I would have retract the whole PR and leave the implementation to someone more knowledgable with celery tasks. 

Let me know what you think about this solution and if you are willing to proceed with this implementation as well for the split.

2024-06-07 15:48 UTC, stumpylog commented
https://docs.celeryq.dev/en/stable/userguide/canvas.html#chains

2024-06-07 17:48 UTC, shamoon commented
> I'm really unsure if it is worth the effort and the complexity. A big challenge will be writing good tests for this. I personally don't see a big value in it, the deletion only happens after a successful merge.

We do not agree. It’s actually not so hard (see celery docs) and there are other examples like this in paperless you could use for how to accomplish it and for tests.

But the larger point here is that as is there is a clear risk of data loss. If the documents are deleted immediately when the document is queued for consumption and then consumption fails (for any of a hundred possible reasons) then we have effectively permanently lost the docs, that is not an acceptable possibility.

No worries if you’re not comfortable taking this PR further, we appreciate your effort either way.

2024-06-07 19:17 UTC, theomega commented
Ok, another attempt, I think I figured this out. Let me know what you think.

2024-06-07 19:19 UTC, shamoon commented
Awesome 👏, we’ll take a look asap

2024-06-07 23:13 UTC, shamoon requested changes
Thanks, this looks good, the changes are just minor things. If you want to include split this is the correct implementation, no worries if not of course.

2024-06-07 23:13 UTC, shamoon commented on src-ui/messages.xlf
> +          <context context-type="linenumber">36</context>
```suggestion
          <context context-type="linenumber">34</context>
```

2024-06-07 23:13 UTC, shamoon commented on src-ui/src/app/components/common/confirm-dialog/merge-confirm-dialog/merge-confirm-dialog.component.html
> +    </div>
```suggestion
    <div class="form-check form-switch mt-4">
      <input class="form-check-input" type="checkbox" role="switch" id="deleteOriginalsSwitch" [(ngModel)]="deleteOriginals" [disabled]="!userOwnsAllDocuments">
      <label class="form-check-label" for="deleteOriginalsSwitch" i18n>Delete original documents after successful merge</label>
    </div>
```

2024-06-07 23:13 UTC, shamoon commented on src/documents/bulk_edit.py
> +        logger.info("Removing original documents after consumption of merged document")
```suggestion
        logger.info("Queueing removal of original documents after consumption of merged document")
```

2024-06-07 23:13 UTC, shamoon commented on src/documents/tasks.py
> +            index.remove_document_by_id(writer, id)
This is just an exact copy of `bulk_edit.py > delete`, I think I'd just use that (DRY).

2024-06-08 16:53 UTC, stumpylog approved these changes
Looks good to me.  No issues in the backend

2024-06-08 16:56 UTC, shamoon approved these changes

2024-06-08 16:56 UTC, merged

2024-06-08 17:14 UTC, theomega commented
Thanks for moving the PR to this stage! Appreciate it!