Add VS Code Devcontainer Configuration for Improved Development Environment Setup
paperless-ngx/paperless-ngx pull request #7041
Opened 2024-06-19 22:24 UTC by p-h-a-i-l

## Proposed change

This pull request adds configuration files for Visual Studio Code devcontainers. Devcontainers provide a consistent and isolated development environment, ensuring that all necessary dependencies and tools are readily available. This setup simplifies the onboarding process for new contributors by reducing the complexity of configuring their development environment, thereby encouraging more contributions.

Closes #6888

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [x] Other. Please explain: Lowers the barrier for contribution by providing a pre-configured development environment. This change has no impact on production code as it only includes configuration files for development setup.

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

2024-06-19 22:33 UTC, stumpylog commented
Generally seems like a good idea.  Can some of the files be integrated into the existing workspace file?

2024-06-19 22:44 UTC, p-h-a-i-l commented
> Generally seems like a good idea. Can some of the files be integrated into the existing workspace file?

The vscode config files in .devcontainer/vscode are not in use on the bare metal route. docker-compose.devcontainer.sqlite-tika.yml just mounts it inside the devcontainer as the active vscode configuration. 
The idea was to avoid interference with bare metal users, but provide easy onboarding for devcontainer users by providing tasks and launch configurations.

2024-06-21 14:02 UTC, stumpylog requested changes

2024-06-21 21:20 UTC, p-h-a-i-l commented on .devcontainer/Dockerfile
> +  "docker/imagemagick-policy.xml", \
done

2024-06-21 21:20 UTC, p-h-a-i-l commented on .devcontainer/docker-compose.devcontainer.sqlite-tika.yml
> +# docker-compose file for running paperless from the docker container registry.
done

2024-06-21 21:20 UTC, p-h-a-i-l commented on .devcontainer/docker-compose.devcontainer.sqlite-tika.yml
> +version: "3.4"
removed

2024-06-21 21:21 UTC, p-h-a-i-l commented on .devcontainer/docker-compose.devcontainer.sqlite-tika.yml
> +    image: docker.io/gotenberg/gotenberg:7.8
done

2024-06-22 13:33 UTC, lobochrome commented
I would love this. I always wanted to commit some japanese specific parsing code - but never could get over installing the dev environment.

2024-06-22 14:16 UTC, p-h-a-i-l commented
> I would love this. I always wanted to commit some japanese specific parsing code - but never could get over installing the dev environment.

Glad you Like it! If you want to help, I am looking for some testers 😬
Maybe there are improvements to be eine in the documentation..

2024-06-23 00:43 UTC, lobochrome commented
I can't commit to proper "testing". But I can sure give it a spin if I find an evening ;).

2024-06-27 14:37 UTC, stumpylog approved these changes
Tested it out and everything seemed to be working alright.  If you could just update the branch, I'll merge this in

2024-06-27 22:13 UTC, merged