Fix #7807
paperless-ngx/paperless-ngx pull request #7808
Opened 2024-09-30 07:50 UTC by mrichtarsky

## Proposed change

Closes #(issue or discussion)

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2024-10-01 15:39 UTC, stumpylog approved these changes

2024-10-01 16:25 UTC, stumpylog requested changes, later dismissed
That's true, might as well test that out

2024-10-03 03:20 UTC, shamoon approved these changes

2024-10-03 03:21 UTC, merged

2024-10-03 05:07 UTC, mrichtarsky commented
Thanks @shamoon for the test, would have been hard to come up with that myself!