Enhancement: use stable unique IDs for custom field select options
paperless-ngx/paperless-ngx pull request #8299
Opened 2024-11-16 18:36 UTC by shamoon

## Proposed change

This is more complicated than I wish, but I think it's 'worth it' to make this change. A lot of the diff is just changing the display and API to the new format, but highlights:

- Instead of using the option index in a list (which can cause inconsistencies which can't be 'detected') we use a unique 16 character ID. I.e. `["apples", "bananas"]` --> [{label: "apples", id:"xxx"}, {label:"bananas", id:"yyy"}]` etc.
    - So number 1 is a db migration to change this and update existing values.
- Finally, when a 'Select' `CustomField` is updated we make sure to prune any values with an ID that no longer exists.

To the user this should all be pretty seamless, see video if curious.

https://github.com/user-attachments/assets/c73ea756-3d5a-4339-9582-d18f688f8eb2

Closes #8271

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2024-12-01 17:24 UTC, stumpylog requested changes

2024-12-01 19:45 UTC, shamoon commented on src/documents/migrations/1057_alter_customfieldinstance_value_select.py
> +            if custom_field.data_type == "select":  # CustomField.FieldDataType.SELECT
Good call yea

2024-12-01 19:45 UTC, shamoon commented on src/documents/serialisers.py
> +                if "id" not in option or option["id"] is None:
sorted thanks!

2024-12-02 03:33 UTC, stumpylog approved these changes

2024-12-02 04:15 UTC, merged