Chore: Switch from os.path to pathlib.Path
paperless-ngx/paperless-ngx pull request #8325
Opened 2024-11-21 19:20 UTC by gothicVI

## Proposed change

Switch some more python files from `os.path` to `pathlib.Path`.

Also, add some type hints.

Related to https://github.com/paperless-ngx/paperless-ngx/discussions/7861

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [x] Other. Please explain: Switch some more python files from `os.path` to `pathlib.Path`.

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2024-11-23 16:31 UTC, shamoon commented
@gothicVI it is generally not necessary to rebase these PRs constantly, it can be left until it is ready to be merged. Thanks

2024-12-04 15:20 UTC, stumpylog requested changes

2024-12-04 15:20 UTC, stumpylog commented on src/documents/classifier.py
> +        hasher: _Hash = sha256()
Just for something basic like this, I don't see a lot of value in typing with a protected item

2024-12-04 15:20 UTC, stumpylog commented on src/documents/classifier.py
> +            tags: list = sorted(
`list[int]` right?

2024-12-04 15:20 UTC, stumpylog commented on src/documents/index.py
> +    if Path(settings.INDEX_DIR).is_dir():
Again should be `Path` already

2024-12-04 15:20 UTC, stumpylog commented on src/documents/index.py
> +    tags: str = ",".join([t.name for t in doc.tags.all()])
Do these add anything?  It should be clear to any type checking tool these are `str`

2024-12-04 15:20 UTC, stumpylog commented on src/documents/management/commands/decrypt_documents.py
> +            with Path(document.source_path).open("wb") as f:
Both source_path and thumbnail_path are already Paths.  This redundant conversion happens a few places

2024-12-04 15:20 UTC, stumpylog commented on src/documents/management/commands/decrypt_documents.py
> +                Path(path).unlink()
Also Paths already

2024-12-04 15:20 UTC, stumpylog commented on src/documents/migrations/1037_webp_encrypted_thumbnail_conversion.py
> +        with Path(existing_encrypted_thumbnail).open("rb") as existing_encrypted_file:
I think the values of the work_package tuple are already Paths

2024-12-04 15:20 UTC, stumpylog commented on src/documents/migrations/1037_webp_encrypted_thumbnail_conversion.py
> +    dependencies: list[tuple[str, str]] = [
I don't think this adds any value

2024-12-04 16:54 UTC, gothicVI commented on src/documents/classifier.py
> +            tags: list = sorted(
I think so

2024-12-04 17:12 UTC, gothicVI commented
@stumpylog I guess some settings are either still strings and/or some tests need to be adapted as well.

2024-12-04 17:21 UTC, stumpylog commented
Yes, you may need to adjust some `override_settings` in the tests, but I would prefer that over extra conversions in the code

2024-12-18 00:46 UTC, shamoon commented
Correct me if Im wrong, but I dont think anyone is looking at this (let alone merging it) until the tests are passing. I can make it a draft for now and you can let us know when its ready.

2024-12-25 10:05 UTC, gothicVI commented
@stumpylog could you take a look at the remaining two failing tests?

I'm not sure I understand why they fail in the first place:

* There shouldn't be any remaining `str` versions of `0000004.pdf.gpg`
* I don't get why `documents/tests/test_api_status.py::TestSystemStatus::test_system_status_classifier_error` fails. It somewhat seems to be related to `src/documents/classifier.py:100` not being able to read which I don't get right now as - as far as I get it - this part of the code wasn't touched.

I've added some artificial fails to try and debug but that "only" told me where it fails.

2024-12-25 18:50 UTC, shamoon requested changes, later dismissed
I dont think `FilePathField` will ever return a Path, will it? So reverting your last two commits then these changes fix that.

For the classifier I would need to find some more time to investigate, that one passes locally for me too

2024-12-25 18:50 UTC, shamoon commented on src/documents/management/commands/decrypt_documents.py
> +            document.filename = document.filename.stem
```suggestion
            document.filename = Path(document.filename).stem
```

2024-12-25 18:50 UTC, shamoon commented on src/documents/management/commands/decrypt_documents.py
> +            ext: str = document.filename.suffix
```suggestion
            ext: str = Path(document.filename).suffix
```

2024-12-26 17:01 UTC, shamoon commented
Please see my changes, obviously feel free to take them or leave them but I think they sort things out. I think they will affect coverage but should be easy to solve that.

2024-12-28 11:16 UTC, gothicVI commented
@shamoon thanks for taking a look!

I'd agree with your patches :+1:

2025-01-04 15:36 UTC, stumpylog commented on src/documents/classifier.py
> +def load_classifier(raise_exception: bool = False) -> Optional["DocumentClassifier"]:
Why the addition of `raise_exception`?

2025-01-04 15:39 UTC, shamoon commented on src/documents/classifier.py
> +def load_classifier(raise_exception: bool = False) -> Optional["DocumentClassifier"]:
That was my suggestion, if you look back at the failing version before I realized the try catch in the status view won’t actually catch anything because the inner part wouldn’t raise anything. Obviously if you have a different approach / solution or whatever feel free!

2025-01-04 20:26 UTC, shamoon commented on src/documents/classifier.py
> +def load_classifier(raise_exception: bool = False) -> Optional["DocumentClassifier"]:
Specifically https://github.com/paperless-ngx/paperless-ngx/pull/8325/commits/4212f6ebede387e010649702f23bedc96c7861ae + https://github.com/paperless-ngx/paperless-ngx/pull/8325/commits/1a942aab25a663eeaf7179db6e0c461b6b563b9f

2025-01-06 19:11 UTC, stumpylog commented on src/documents/classifier.py
> +def load_classifier(raise_exception: bool = False) -> Optional["DocumentClassifier"]:
Ok, only request would be to make it keyword only for clarity.  Not sure why I haven't enabled [FBT002](https://docs.astral.sh/ruff/rules/boolean-default-value-positional-argument/#boolean-default-value-positional-argument-fbt002)

2025-01-06 19:24 UTC, stumpylog commented on src/documents/classifier.py
> +def load_classifier(raise_exception: bool = False) -> Optional["DocumentClassifier"]:
Might as well be all the FBT.  I think I did just some rules, but maybe there are others which can help keep things clean.

2025-01-06 19:25 UTC, stumpylog approved these changes

2025-01-06 20:12 UTC, merged