fix postCreateCommand
paperless-ngx/paperless-ngx pull request #8542
Opened 2024-12-23 06:25 UTC by orcema

## Proposed change

Closes discussion #(#8462 )

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

2024-12-23 06:46 UTC, shamoon reviewed
Isn’t pre-commit already in the dev packages in the pipfile?

2024-12-23 12:31 UTC, orcema commented
you are right, but then i don't understand the presence of this command "/bin/bash -c pre-commit install" in the devcontainer.json ?
Should i simply remove the pipenv install pre-commit ?

2024-12-23 14:13 UTC, shamoon commented
> you are right, but then i don't understand the presence of this command "/bin/bash -c pre-commit install" in the devcontainer.json ? Should i simply remove the pipenv install pre-commit ?

Yes that’s what I was thinking, that command initializes pre-commit which shouldn’t be necessary. But I guess the question is did you test this PR?

2024-12-23 21:53 UTC, shamoon commented
> yes i worked for me but it installed twice the pre-commit one explicitly and once by with the package :-)

Again `pre-commit install` doesn't install it, it initializes that tool (which is unnecessary). If you want to remove that part that would be fine.

2024-12-24 12:31 UTC, orcema commented
My mistake, the pull request proposes the correction as: 
`"postCreateCommand": "pipenv install --dev && pipenv install pre-commit",`
but i have to replace "_pipenv install pre-commit_" with "_pipenv run pre-commint install_" ?
**According to dev instructions:**
link to instructions: [pre-commit install](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docs/development.md#:~:text=%24-,pre%2Dcommit%20install,-Apply%20migrations%20and)

2024-12-24 14:57 UTC, orcema commented
ok i figured out that the **pre-commit install** has not been executed in my dev container and this allowed me to push the commit above.
Due to an known issue for Macbook Docker [https://github.com/docker/for-mac/issues/5029](https://github.com/docker/for-mac/issues/5029) i wouldn't have been able to commit changes.
Thus i propose with commit [e398ade](https://github.com/paperless-ngx/paperless-ngx/pull/8542/commits/e398adeebe40627d10f96005d6e8e7aad7866195) to remove the check for **check-executables-have-shebangs**

2024-12-24 15:01 UTC, orcema commented
and the final fix the [335a6d2](https://github.com/paperless-ngx/paperless-ngx/pull/8542/commits/335a6d2709bd672ef13a5918f35af59456cde43c) for the  
**postCreateCommand**

2024-12-24 15:30 UTC, orcema commented
for devcontainer i had one more issue regarding the Angular frontend. if i do not specify to bind to host 0.0.0.0 i'm not able to connect to the frontend. I did analyse the network traffic there was no response from the container when trying to connect to http://localhost:4200/

2024-12-24 16:12 UTC, shamoon requested changes

2024-12-24 16:12 UTC, shamoon commented on .pre-commit-config.yaml
I dont think we should disable this just because it causes a devcontainer issue on MBP users. Perhaps theres another workaround but that is not an acceptable trade-off. Also, I use a Mac Studio and MBP and dont have any issue, but anyway, this change should be reverted

2024-12-25 00:11 UTC, orcema commented on .pre-commit-config.yaml
but this is a blocking issue when using devcontainers on a macbook because no commits are possible anymore ?

2024-12-25 00:32 UTC, orcema commented on .pre-commit-config.yaml
would it be acceptable to setup this fake shebang line at the top of the file .pre-commit-config.yaml like this

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/44d70de2-52a1-47ce-b397-a1e7c2638cee" />

2024-12-25 01:31 UTC, shamoon commented on .pre-commit-config.yaml
While it’s a little rude for my liking, I think this comment says it well:

https://github.com/pre-commit/identify/pull/189#issuecomment-808854232

There are other workarounds such as https://github.com/docker/for-mac/issues/5029#issuecomment-2481393246 or maybe something else but the point is the issue affects no one but you whereas the proposed solution changes a lint rule for the entire project, that’s not an acceptable trade-off. I’m not a big fan of the shebang hack either

2024-12-25 07:14 UTC, orcema commented on .pre-commit-config.yaml
ok, as you decide, the point is this affects not only me but anyone with a mac willing to use the devcontainer solution. I have also a bunch of enhancement ready to commit for using devcontainer but I'm locked out because of a shebang comment line :-).
If this is your final decision i d'ont see any other solution than forking the project for macusers willing to develop with devcontainers.

2024-12-25 07:57 UTC, shamoon commented on .pre-commit-config.yaml
Again, https://github.com/docker/for-mac/issues/5029#issuecomment-2481393246 fixes it

```sh
paperless@7d3b82fc893b:~/paperless-ngx$ git add .
paperless@7d3b82fc893b:~/paperless-ngx$ git commit -m "Revert pre-commit rule change"
check docstring is first.............................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check yaml...............................................................Passed
check toml...........................................(no files to check)Skipped
check that executables have shebangs.................(no files to check)Skipped
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
check for case conflicts.................................................Passed
detect private key.......................................................Passed
codespell................................................................Passed
prettier.............................................(no files to check)Skipped
ruff.................................................(no files to check)Skipped
ruff-format..........................................(no files to check)Skipped
Hadolint.............................................(no files to check)Skipped
beautysh.............................................(no files to check)Skipped
shellcheck...........................................(no files to check)Skipped
```

You can also run git outside the container and it seems to work

2024-12-25 08:33 UTC, orcema commented on .pre-commit-config.yaml
I tried the **Docker VMM** and it resolved my issue.

2024-12-25 08:39 UTC, orcema commented
changes to "[.pre-commit-config.yaml](https://github.com/paperless-ngx/paperless-ngx/pull/8542/files/15f7681df6e7863c060b1158ba9b5f2f496c7565#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9)" reverted

2024-12-25 08:45 UTC, shamoon approved these changes

2024-12-25 08:53 UTC, merged